import './globals.css'

import type { Metadata } from 'next'
import { Poppins } from 'next/font/google'
import React from 'react'

const poppins = Poppins({
  weight: ['100', '200', '300', '400', '500', '600', '700', '800', '900'],
  style: ['normal', 'italic'],
  subsets: ['devanagari', 'latin', 'latin-ext'],
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en" className="min-h-screen bg-background font-sans antialiased">
      <body className={poppins.className}>
        <main className="">{children}</main>
      </body>
    </html>
  )
}
